name: flutter_xupdate
description: A Flutter plugin for XUpdate(Android Version Update Library).
version: 1.0.2
homepage: https://github.com/xuexiangjys/flutter_xupdate
repository: https://github.com/xuexiangjys/flutter_xupdate
issue_tracker: https://github.com/xuexiangjys/flutter_xupdate/issues

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter
  g_package_info:
    git:
      url: https://github.com/msidolphin/flutter_package_info
      ref: '2.0.1'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.xuexiang.flutter_xupdate
        pluginClass: FlutterXUpdatePlugin